---
title: "Untitled"
author: "Rodrigo Citton P. dos Reis"
date: "03/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(printr)
```

## R Markdown

```{r}
# Sexo

sexo <- c(rep(0, 200000), rep(1, 200000))
sexo <- factor(sexo, labels = c("Mulheres", "Homens"))

# Idade

idade <- c(rep(c(0, 1), each = 100000), rep(c(0, 1), each = 100000))
idade <- factor(idade, labels = c("Jovens", "Idosos"))

# Estrato

df <- data.frame(sexo, idade)

df$estrato <- ifelse(df$sexo == "Homens" & df$idade == "Idosos", 1,
                     ifelse(df$sexo == "Mulheres" & df$idade == "Idosos", 2,
                            ifelse(df$sexo == "Homens" & df$idade == "Jovens", 3, 4)))

# Desfecho

df$desfecho <- 0
df$desfecho[df$estrato == 1][1:40000] <- 1
df$desfecho[df$estrato == 2][1:30000] <- 1
df$desfecho[df$estrato == 3][1:20000] <- 1
df$desfecho[df$estrato == 4][1:10000] <- 1

df$desfecho <- factor(df$desfecho, labels = c("Vivo", "Morto"))

# Grupo de tratamento

df$grupo <- ifelse(df$idade == "Idosos", 
                   rbinom(n = 100000, size = 1, prob = 0.8),
                   rbinom(n = 100000, size = 1, prob = 0.2))
df$grupo <- factor(df$grupo, labels = c("Controle", "Tratado"))

df$estrato <- factor(df$estrato, labels = paste("Estrato", 1:4))
df$desfecho <- relevel(df$desfecho, ref = "Morto")
df$grupo <- relevel(df$grupo, ref = "Tratado")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE, echo=TRUE, results='asis'}
tab <- table(df$grupo, df$desfecho, df$estrato, dnn = c("Grupo", "Desfecho", "Estrato"))
tab <- addmargins(tab, margin = 2)
tab <- ftable(tab, row.vars = c(3, 1))
stargazer::stargazer(format(tab, quote=FALSE, justify="right"), type="html")
```

